[config]
schemaVersion = "0.0.1"

[package]
namespace = "DET"
name = "DivineExpansion"
versionNumber = "0.0.1"
description = "Adds gods to Hades 2"
websiteUrl = "https://github.com/Kuipo/DivineExpansion"
containsNsfwContent = false

[package.dependencies]
Hell2Modding-Hell2Modding = "1.0.74"
SGG_Modding-SJSON = "1.0.0"
SGG_Modding-ModUtil = "4.0.1"
zannc-GodsAPI = "1.0.1"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[[build.copy]]
source = "./src"
target = "./plugins"

[[build.copy]]
source = "./packages"
target = "./plugins_data"

[publish]
repository = "https://thunderstore.io"
communities = [ "hades-ii", ]

[publish.categories]
hades-ii = [ "mods", ]
